### ISSUE TITLE
ERROR   File reading error: open /sys/devices/

### ISSUE THREAD

**Issue by Schlaefer** [markusressel/fan2go#38]
I just wanted to run a calibration on new fans and thought I update to the latest master (c43784e215fd74f22bc37957fbd45df9bdbe4c14)  for prosperity. I currently get:

```
███████  █████  ███    ██ ██████   ██████   ██████  
██      ██   ██ ████   ██      ██ ██       ██    ██ 
█████   ███████ ██ ██  ██  █████  ██   ███ ██    ██ 
██      ██   ██ ██  ██ ██ ██      ██    ██ ██    ██ 
██      ██   ██ ██   ████ ███████  ██████   ██████  

INFO  Using configuration file at: /etc/fan2go/fan2go.yaml
ERROR   File reading error: open /sys/devices/platform/f71882fg.656/pwm3_enable: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55eda1]

goroutine 1 [running]:
github.com/markusressel/fan2go/internal.createFans({0xc00025e240, 0x22})
/home/siezi/Downloads/JD/fan2go-0.0.17/internal/backend.go:600 +0x3c1
github.com/markusressel/fan2go/internal.FindControllers()
/home/siezi/Downloads/JD/fan2go-0.0.17/internal/backend.go:547 +0x248
github.com/markusressel/fan2go/internal.Run(0x0)
/home/siezi/Downloads/JD/fan2go-0.0.17/internal/backend.go:48 +0xcb
github.com/markusressel/fan2go/cmd.glob..func1(0x9f5440, {0x759b45, 0x2, 0x2})
/home/siezi/Downloads/JD/fan2go-0.0.17/cmd/root.go:41 +0x65
github.com/spf13/cobra.(*Command).execute(0x9f5440, {0xc000012190, 0x2, 0x2})
/home/siezi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x9f5440)
/home/siezi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
/home/siezi/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/markusressel/fan2go/cmd.Execute()
/home/siezi/Downloads/JD/fan2go-0.0.17/cmd/root.go:248 +0x2a6
main.main()
/home/siezi/Downloads/JD/fan2go-0.0.17/main.go:25 +0x17
```

Rolling back to to the last known good 7a7260a03c5b3c304d51c588ce1ea4f0e09fd2c6 still works fine. 

```
ls /sys/devices/platform/f71882fg.656/pwm*
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm1
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm1_enable
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm1_interpolate
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_channels_temp
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point1_pwm
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point1_temp
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point1_temp_hyst
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point2_pwm
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point2_temp
-r--r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point2_temp_hyst
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point3_pwm
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point3_temp
-r--r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point3_temp_hyst
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point4_pwm
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point4_temp
-r--r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point4_temp_hyst
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_auto_point5_pwm
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_enable
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm2_interpolate
-rw-r--r-- 1 root root 4096  4. Okt 08:42 /sys/devices/platform/f71882fg.656/pwm3
```

Pwm3 is a AIO header which can't be controlled by the linux driver, it just exists at always on 100%.

PS: Just as a datapoint, feel free to close. :+1:

**Comment by markusressel** [comment]
Closing this in favor of #48
