### ISSUE TITLE
Segmentation Fault when there is a typo in the config

### ISSUE THREAD

**Issue by SyedAmerGilani** [markusressel/fan2go#42]
I made a typo in the config under fan:sensor: which resulted in a segmentation fault:

```
 INFO  Starting controller loop for fan 'cpu_fan' (hwmon3, pwm2)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x5a6130]

goroutine 7 [running]:
github.com/markusressel/fan2go/internal.calculateOptimalPwm(...)
	/github/workspace/internal/backend.go:701
github.com/markusressel/fan2go/internal.fanController(0xa9d8a0, 0xc00020d440, 0xc0001d2000, 0xc0001e4400, 0xc000420120, 0x1, 0xc000020040)
	/github/workspace/internal/backend.go:340 +0x680
github.com/markusressel/fan2go/internal.Run.func5(0x0, 0x0)
	/github/workspace/internal/backend.go:102 +0x117
github.com/oklog/run.(*Group).Run.func1(0xc000068060, 0xc00034d440, 0xc0003e8640)
	/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:38 +0x27
created by github.com/oklog/run.(*Group).Run
	/go/pkg/mod/github.com/oklog/run@v1.1.0/group.go:37 +0xbb
```
Here are the Full Log and Configuration File i used.

[fan2go.yml.txt](https://github.com/markusressel/fan2go/files/7408432/fan2go.yml.txt)
[full.log](https://github.com/markusressel/fan2go/files/7408408/full.log)

**Comment by markusressel** [comment]
I have added some config validation logic in `0.1.0`, please give it a try.
